version: '3.4'

services:
  tfg.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__OrdersDb=${PAYROLL_CONNECTIONSTRING:-Data Source=tfg.orders.sqlserver;Initial Catalog=TFG.Orders;User ID=sa;Password=Pass@word!;TrustServerCertificate=True}
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - tfg-orders-network
    
  tfg.orders.sqlserver:
    user: root
    environment:
      - SA_PASSWORD=${SA_PASSWORD:-Pass@word!}
      - SA_USER=${SA_USER:-sa}
      - ACCEPT_EULA=Y
    ports:
      - "5444:1433"
    volumes:
      - ./config/sql:/var/opt/mssql/data
    networks:
      - tfg-orders-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U $${SA_USER} -P "$${SA_PASSWORD}" -Q "select 1" || exit 1
      interval: 5s
      retries: 3

networks:
  tfg-orders-network:
    driver: bridge
    name: tfg-orders-network