apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-dply
spec:
  selector:
    matchLabels:
      app: orders
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
        tier: backend
        track: stable
    spec:
      containers:
        - name: orders
          image: docker.io/wadrydev/tfgorders
          env:
          - name: ConnectionStrings__OrdersDb
            value: Data Source=host.minikube.internal,5444;Initial Catalog=TFG.Orders;User ID=sa;Password=Pass@word!;TrustServerCertificate=True
          ports:
            - name: http
              containerPort: 80