apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfgorders-deployment
spec:
  selector:
    matchLabels:
      app: tfgorders-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: tfgorders-pod
    spec:
      containers:
      - image: docker.io/wadrydev/tfgorders
        name: tfgorders-container
        resources: {}
        ports:
          - containerPort: 80 